### ISSUE TITLE
FastRouteRouter->addRoute() does not throw a RuntimeException of called after either match() or geerateUri()

### ISSUE THREAD

**Issue by weierophinney** [mezzio/mezzio-fastroute#2]
- [x] I was not able to find an [open](https://github.com/zendframework/zend-expressive-fastroute/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-expressive-fastroute/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [x] This is not a question. (Questions should be asked on [slack](https://zendframework.slack.com/) ([Signup for Slack here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).)

The `Zend\Expressive\Router\RouterInface` states on `addRoute()`:
```
    /**
     * ...
     *
     * The method MUST raise Exception\RuntimeException if called after either `match()`
     * or `generateUri()` have already been called, to ensure integrity of the
     * router between invocations of either of those methods.
     *
     * @throws Exception\RuntimeException when called after match() or
     *     generateUri() have been called.
     */
    public function addRoute(Route $route) : void;
```

But no RuntimeException will be thrown / raised.

### Code to reproduce the issue

```php
class TestMiddleware implements \Psr\Http\Server\MiddlewareInterface
{
  public function process(ServerRequestInterface $request, RequestHandlerInterface $handler): ResponseInterface {
    return $handler->handle($request);
  }
}

$router = new \Zend\Expressive\Router\FastRouteRouter();
$router->addRoute('/test', new TestMiddleware());
$router->match($request);
$router->addRoute('/test2', new TestMiddleware());
```

### Expected results

A `Zend\Expressive\Router\Exception\RuntimeException` is thrown indicating that no routes may be added after calling `match()`.

### Actual results

Scripts run without an exception.

### Consequences

Is this a bug in the RouterInterface of "zend-expressive-router" or in the FastRouteRouter of this repo? 
(Same "error" (?) is in the "zend-expressive-zendrouter").

---

Originally posted by @MatthiasKuehneEllerhold at https://github.com/zendframework/zend-expressive-fastroute/issues/60

**Comment by weierophinney** [comment]
I guess this is a typo or something that's never implemented. I've checked all routers and they all do this (including older versions):
```
    public function addRoute(Route $route) : void
    {
        $this->routesToInject[] = $route;
    }
```
I guess you can even call it a feature to add more routes after you matched a route already :)

And to be honest, why would you have that check? When adding a lot of routes it only creates overhead.

---

Originally posted by @geerteltink at https://github.com/zendframework/zend-expressive-fastroute/issues/60#issuecomment-425995923

**Comment by weierophinney** [comment]
So it'd be fine to remove this part of the docblock from zend-expressive?

---

Originally posted by @MatthiasKuehneEllerhold at https://github.com/zendframework/zend-expressive-fastroute/issues/60#issuecomment-426150070

**Comment by alexmerlin** [comment]
Closing issue due to being inactive for more than 1 year.
